#!/bin/bash
# Package information
packager="gavinpease AT gmail DOT com"
name=systemd
major_version=247
min_version=
rel_version=
download=https://github.com/systemd/systemd/archive/v247/systemd-247.tar.gz

# Some nice envionment variables
prev_dir=$PWD
srcfolder=$name-src
tmpname=/tmp/yoink/$name

function get_source() {
	mkdir $srcfolder
	builtin cd $srcfolder
	wget $download
	file=$(ls)
	tar xf $file 
	rm $file
	file=$(ls)
	builtin cd $file
}

# Put all of your pre-compilation configuration here.
function config() {
	sed -i 's/GROUP="render", //' rules.d/50-udev-default.rules.in
	mkdir build &&
	cd    build &&

	meson --prefix=$tmpname/usr                 \
	      -Dblkid=true                  \
	      -Dbuildtype=release           \
	      -Ddefault-dnssec=no           \
	      -Dfirstboot=false             \
	      -Dinstall-tests=false         \
	      -Dldconfig=false              \
	      -Dman=auto                    \
	      -Drootprefix=                 \
	      -Drootlibdir=$tmpname/lib             \
	      -Dsplit-usr=true              \
	      -Dsysusers=false              \
	      -Drpmmacrosdir=no             \
	      -Db_lto=false                 \
	      -Dhomed=false                 \
	      -Duserdb=false                \
	      -Dmode=release                \
	      -Dpamconfdir=/etc/pam.d       \
	      -Ddocdir=/usr/share/doc/systemd-247 \
	      ..  	
}

# Put build commands here.
function build() {
	ninja
}

# Only change the line that says `make install`
function build_install() {
	sudo mkdir $tmpname -p
	ninja install 
}

function gen_tree(){
	currdir=$PWD
	builtin cd $tmpname
	sudo sh -c "find -not -name 'install.sh' -not -name '.TREE' -printf '%P\n' > .TREE";
	builtin cd $currdir
}
 # If you need to set permissions to different files, do so here, and do the relative directories.
function set_permissions(){
	/bin/true
}
# Put post-build commands here.
function post_build(){
	builtin cd $tmpname
	# Add links/files here.
	
	#
	[[ -f $prev_dir/install.sh ]] && cp $prev_dir/install.sh $tmpname
 	gen_tree	
	set_permissions
	sudo chown root:root -R .
	find $tmpname/usr/lib -type f -name \*.a \
	    -exec strip --strip-debug {} ';'
	find $tmpname/lib $tmpname/usr/lib -type f -name \*.so* ! -name \*dbg \
	    -exec strip --strip-unneeded {} ';'
	find $tmpname/{bin,sbin} $tmpname/usr/{bin,sbin,libexec} -type f \
	    -exec strip --strip-all {} ';'
	if [[ ! -z $rel_version ]]; then
		tar --exclude=./ -P -czf /tmp/$name-$major_version.$min_version.$rel_version.tar.gz ./
	elif [[ ! -z $min_version ]]; then
                tar --exclude=./ -P -czf /tmp/$name-$major_version.$min_version.tar.gz ./
        else
                tar --exclude=./ -P -czf /tmp/$name-$major_version.tar.gz ./
        fi
	
	cd $prev_dir
	#sudo rm -rf $tmpname
	#rm -rf $srcfolder

}
export -f get_source
export -f config
export -f build
export -f build_install
export -f post_build
